# Generated by Django 6.0.1 on 2026-03-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
