# Generated by Django 6.0.1 on 2026-03-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
