# Generated by Django 6.0.1 on 2026-03-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='license_plate',
        ),
    ]
